# Generated by Django 4.2.7 on 2023-12-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceptbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionlog',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
