name: Deploy to PyPI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Replace '3.8' with the Python version you are using
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install setuptools wheel twine
    - name: Run tests
      run: |
        # Add commands to run your tests, for example:
        # pytest
        # or for Django project:
        python manage.py test
    - name: Publish to PyPI
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
# You must configure PYPI_USERNAME and PYPI_PASSWORD in the secrets settings of your repository.